package net.ausiasmarch.seguromedico.gui;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import net.ausiasmarch.common.Convert;
import net.ausiasmarch.seguromedico.modelo.SeguroMedico;

/**
 *
 * @author Pixel_Zer0
 */
public class Main extends javax.swing.JFrame {

    private final SeguroMedico seguroMedido;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        seguroMedido = new SeguroMedico();

        iniciar();

    }

    private void iniciar() {        
        jScrollPaneErrores.setVisible(false);
        setSize(650, 370);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxCoberturaCorazon = new javax.swing.JCheckBox();
        jCheckBoxCoberturaInVitro = new javax.swing.JCheckBox();
        jCheckBoxCoberturaDermatologia = new javax.swing.JCheckBox();
        jCheckBoxPediatria = new javax.swing.JCheckBox();
        jCheckBoxCoberturaOftalmologia = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxEnfermedadCorazon = new javax.swing.JCheckBox();
        jCheckBoxEnfermedadOjos = new javax.swing.JCheckBox();
        jCheckBoxEnfermedadPiel = new javax.swing.JCheckBox();
        jTextFieldNumHijos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxEmbarazada = new javax.swing.JCheckBox();
        jButtonCalcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldImporteAnual = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxTrabajo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldImporteMensual = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPaneErrores = new javax.swing.JScrollPane();
        jTextAreaListaErrores = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPrecioBase = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contratación de Seguro Médico");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEdad.setText("Edad:");
        getContentPane().add(jLabelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, 25));
        getContentPane().add(jTextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 60, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Coberturas Ampliadas"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBoxCoberturaCorazon.setText("Corazón");
        jPanel1.add(jCheckBoxCoberturaCorazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jCheckBoxCoberturaInVitro.setText("Fecundación in vitro");
        jPanel1.add(jCheckBoxCoberturaInVitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jCheckBoxCoberturaDermatologia.setText("Dermatología");
        jPanel1.add(jCheckBoxCoberturaDermatologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jCheckBoxPediatria.setText("Pediatría");
        jPanel1.add(jCheckBoxPediatria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jCheckBoxCoberturaOftalmologia.setText("Oftalmología");
        jPanel1.add(jCheckBoxCoberturaOftalmologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 620, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()), "Enfermedades"));

        jCheckBoxEnfermedadCorazon.setText("Corazón");

        jCheckBoxEnfermedadOjos.setText("Ojos");

        jCheckBoxEnfermedadPiel.setText("Piel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jCheckBoxEnfermedadCorazon)
                .addGap(138, 138, 138)
                .addComponent(jCheckBoxEnfermedadOjos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(jCheckBoxEnfermedadPiel)
                .addGap(91, 91, 91))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxEnfermedadCorazon)
                    .addComponent(jCheckBoxEnfermedadOjos)
                    .addComponent(jCheckBoxEnfermedadPiel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 620, 60));
        getContentPane().add(jTextFieldNumHijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 40, 20));

        jLabel2.setText("Nº Hijos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 25));

        jCheckBoxEmbarazada.setText("Embarazada");
        getContentPane().add(jCheckBoxEmbarazada, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 100, -1));

        jLabel4.setText("Importe Anual:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 20));

        jTextFieldImporteAnual.setEditable(false);
        jTextFieldImporteAnual.setBackground(new java.awt.Color(153, 255, 153));
        jTextFieldImporteAnual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldImporteAnual.setFocusable(false);
        getContentPane().add(jTextFieldImporteAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 90, 20));

        jLabel10.setText("Trabajo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, 20));

        jComboBoxTrabajo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Funcionario", "Contratado", "Autónomo" }));
        getContentPane().add(jComboBoxTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 130, -1));

        jLabel7.setText("€");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 10, 20));

        jLabel5.setText("Importe Mensual:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 20));

        jTextFieldImporteMensual.setEditable(false);
        jTextFieldImporteMensual.setBackground(new java.awt.Color(153, 255, 153));
        jTextFieldImporteMensual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldImporteMensual.setFocusable(false);
        getContentPane().add(jTextFieldImporteMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 90, 20));

        jLabel8.setText("€");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 10, 20));

        jTextAreaListaErrores.setEditable(false);
        jTextAreaListaErrores.setBackground(new java.awt.Color(255, 241, 222));
        jTextAreaListaErrores.setColumns(20);
        jTextAreaListaErrores.setLineWrap(true);
        jTextAreaListaErrores.setRows(5);
        jTextAreaListaErrores.setBorder(javax.swing.BorderFactory.createTitledBorder(" Se han encontrado los siguientes errores "));
        jTextAreaListaErrores.setFocusable(false);
        jTextAreaListaErrores.setMaximumSize(new java.awt.Dimension(110, 37));
        jTextAreaListaErrores.setName(""); // NOI18N
        jScrollPaneErrores.setViewportView(jTextAreaListaErrores);

        getContentPane().add(jScrollPaneErrores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 580, 130));

        jLabel11.setText("Género:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 70, 20));

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer" }));
        getContentPane().add(jComboBoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 100, -1));

        jLabel1.setText("Precio Base:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jTextFieldPrecioBase.setText("200");
        getContentPane().add(jTextFieldPrecioBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 80, 20));

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed

        // Declaramos las variables de entrada
        int edad, numHijos;
        
        // Declaramos las variables de salida provenientes de "SeguroMedico"
        double precioBase, importeMensual, importeAnual;
        
        // Declaramos el contenedor de strings con los errores de salida
        StringBuilder sb = new StringBuilder();
        
        // Limpiamos la salida de los resultados
        jTextFieldImporteMensual.setText("");
        jTextFieldImporteAnual.setText("");
        
        // Obtenemos y validamos los datos de entrada
        
        // Si el precio base no es un número válido
        if (!Convert.isValidDouble(jTextFieldPrecioBase.getText())) {
            sb.append("  - Precio base no válido.\n");
        }
        
        // Si la edad no es válida
        if (!Convert.isValidInt(jTextFieldEdad.getText())) {
            sb.append("  - Edad no válida.\n");
        }
        
        // Si el núm de hijos no es válido
        if (!Convert.isValidInt(jTextFieldNumHijos.getText())) {
            sb.append("  - Nº de hijos no válido.\n");
        }
        
        // Si hay errores, mostrarlos
        if (sb.length() > 0) {
            setSize(637, 539);
            jScrollPaneErrores.setVisible(true);
            jTextAreaListaErrores.setText("");
            jTextAreaListaErrores.append(sb.toString());
            jTextAreaListaErrores.setCaretPosition(0);
            return;
        }
        
        // Hacemos las conversiones de los datos numéricos
        precioBase = Convert.parseDouble(jTextFieldPrecioBase.getText());
        edad = Convert.parseInt(jTextFieldEdad.getText());
        numHijos = Convert.parseInt(jTextFieldNumHijos.getText());
        
        // Pasamos los datos de entrada a "SeguroMedico"
        seguroMedido.setPrecioBase(precioBase);
        seguroMedido.setEdad(edad);
        seguroMedido.setNumHijos(numHijos);
        
        // Pasamos las opciones elegidas en los desplegables
        seguroMedido.setGenero(jComboBoxGenero.getSelectedItem().toString());
        seguroMedido.setTrabajo(jComboBoxTrabajo.getSelectedItem().toString());
        
        // Pasamos las opciones de los CheckBox
        seguroMedido.setEmbarazada(jCheckBoxEmbarazada.isSelected());
        seguroMedido.setEnfermedadCorazon(jCheckBoxEnfermedadCorazon.isSelected());
        seguroMedido.setEnfermedadOjos(jCheckBoxEnfermedadOjos.isSelected());
        seguroMedido.setEnfermedadPiel(jCheckBoxEnfermedadPiel.isSelected());
        seguroMedido.setCoberturaCorazon(jCheckBoxCoberturaCorazon.isSelected());
        seguroMedido.setCoberturaOftalmologica
                (jCheckBoxCoberturaOftalmologia.isSelected());
        seguroMedido.setCoberturaInVitro(jCheckBoxCoberturaInVitro.isSelected());
        seguroMedido.setCoberturaPediatria(jCheckBoxPediatria.isSelected());
        seguroMedido.setCoberturaDermatologia
                (jCheckBoxCoberturaDermatologia.isSelected());
        
        // Comprobamos que el seguro es válido
        if (seguroMedido.validate() == false) {
        sb.append(seguroMedido.getMensaje());
        setSize(637, 539);
        jScrollPaneErrores.setVisible(true);
        jTextAreaListaErrores.setText("");
        jTextAreaListaErrores.append(sb.toString());
        jTextAreaListaErrores.setCaretPosition(0);
        return;
        }
        
        // Si llegamos aqui todo es correcto
        // Obtenemos cálculos desde el objeto hipoteca
        importeMensual = seguroMedido.importeMensual();
        importeAnual = seguroMedido.importeAnual();
        
        // Mostramos los resultados con el formato adecuado
        jTextFieldImporteMensual.setText(Convert.format(importeMensual, 2));
        jTextFieldImporteAnual.setText(Convert.format(importeAnual, 2));
        setSize(650, 370);
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextFieldPrecioBase.setText("200");
        jTextFieldEdad.setText("");
        jTextFieldNumHijos.setText("");
        jComboBoxGenero.setSelectedItem("Hombre");
        jComboBoxTrabajo.setSelectedItem("Funcionario");
        jCheckBoxEmbarazada.setSelected(false);
        jCheckBoxEnfermedadCorazon.setSelected(false);
        jCheckBoxEnfermedadOjos.setSelected(false);
        jCheckBoxEnfermedadPiel.setSelected(false);
        jCheckBoxCoberturaCorazon.setSelected(false);
        jCheckBoxCoberturaOftalmologia.setSelected(false);
        jCheckBoxPediatria.setSelected(false);
        jCheckBoxCoberturaInVitro.setSelected(false);
        jCheckBoxCoberturaDermatologia.setSelected(false);
        jTextFieldImporteMensual.setText("");
        jTextFieldImporteAnual.setText("");
        jScrollPaneErrores.setVisible(false);
        jTextAreaListaErrores.setText("");
        setSize(650, 370);

    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void mensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            String look = UIManager.getSystemLookAndFeelClassName();
            javax.swing.UIManager.setLookAndFeel(look);

        } catch (ClassNotFoundException | InstantiationException |
                IllegalAccessException | UnsupportedLookAndFeelException ex) {
            throw new RuntimeException(ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JCheckBox jCheckBoxCoberturaCorazon;
    private javax.swing.JCheckBox jCheckBoxCoberturaDermatologia;
    private javax.swing.JCheckBox jCheckBoxCoberturaInVitro;
    private javax.swing.JCheckBox jCheckBoxCoberturaOftalmologia;
    private javax.swing.JCheckBox jCheckBoxEmbarazada;
    private javax.swing.JCheckBox jCheckBoxEnfermedadCorazon;
    private javax.swing.JCheckBox jCheckBoxEnfermedadOjos;
    private javax.swing.JCheckBox jCheckBoxEnfermedadPiel;
    private javax.swing.JCheckBox jCheckBoxPediatria;
    private javax.swing.JComboBox jComboBoxGenero;
    private javax.swing.JComboBox jComboBoxTrabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneErrores;
    private javax.swing.JTextArea jTextAreaListaErrores;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldImporteAnual;
    private javax.swing.JTextField jTextFieldImporteMensual;
    private javax.swing.JTextField jTextFieldNumHijos;
    private javax.swing.JTextField jTextFieldPrecioBase;
    // End of variables declaration//GEN-END:variables

}
