/*
 * HabitacionVista1.java
 */

package net.ausiasmarch.habitacion.modelo;

import java.awt.Component;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.geom.AffineTransform;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JLabel;


/**
 *
 * @author Luis
 */
public class Habitacion extends javax.swing.JPanel {

    /** Creates new form HabitacionVista1 */
    public Habitacion() {
        initComponents();
        this.setVisible(true);


        for (int i = 0; i < this.getComponentCount(); i++) {
            Component component = this.getComponent(i);
            if ((component instanceof JLabel) && (component != jLabelFondoV1)) {
                JLabel jLabel = (JLabel) component;
                jLabel.setVisible(false);
                if (jLabel.getIcon() != null)  {
                    String nombre = jLabel.getIcon().toString().substring(0,
                            jLabel.getIcon().toString().length() - 4);
                    int pos = nombre.lastIndexOf('/');
                    nombre = nombre.substring(pos + 1);
                    System.out.println(nombre + " = " + i);
                }
            }
        }
    }

    private Font getLedFont() {
        Font font;
        InputStream is;
        String path = "net/ausiasmarch/habitacion/recursos/LED_REAL.TTF";
        ClassLoader cl = this.getClass().getClassLoader();
        if (cl == null) {
            is = ClassLoader.getSystemResourceAsStream(path);
        } else {
            is = cl.getResourceAsStream(path);
        }
        try {
            font = Font.createFont(Font.TRUETYPE_FONT, is);
        } catch (FontFormatException | IOException ex) {
            throw new RuntimeException(ex);
        }
        AffineTransform at = new AffineTransform();
        at.rotate(Math.toRadians(10));

        return font.deriveFont(Font.BOLD,20).deriveFont(at);
    }

    /**
     * Agregar un aparato a la habitación
     * @param aparato
     */
    public void agregarAparato(Aparato aparato) {
        aparato.setHabitacion(this);
    }

    public Component getContentComponent(int index) {
        return this.getComponent(index);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeLuceslEntrada = new javax.swing.JLabel();
        jLabelLucesMesa = new javax.swing.JLabel();
        jLabelLucesMueble01 = new javax.swing.JLabel();
        jLabelLucesMueble02 = new javax.swing.JLabel();
        jLabelLucesMueble03 = new javax.swing.JLabel();
        jLabelLucesComedor1 = new javax.swing.JLabel();
        jLabelLucesComedor2 = new javax.swing.JLabel();
        jLabelLucesSofa = new javax.swing.JLabel();
        jLabelPersiana1 = new javax.swing.JLabel();
        jLabelPersiana2 = new javax.swing.JLabel();
        jLabelPersiana3 = new javax.swing.JLabel();
        jLabelPersiana4 = new javax.swing.JLabel();
        jLabelAireAcondicionado = new javax.swing.JLabel();
        jLabelRadiador = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        jLabelTelevisor1 = new javax.swing.JLabel();
        jLabelTiempoCM = new javax.swing.JLabel();
        jLabelMiniCadena1 = new javax.swing.JLabel();
        jLabelTiempoBR = new javax.swing.JLabel();
        jLabelBlueRay1 = new javax.swing.JLabel();
        jLabelFondoV1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeLuceslEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/lucesEntrada.png"))); // NOI18N
        add(jLabeLuceslEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 206, -1, -1));

        jLabelLucesMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLucesMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/lucesMesa.png"))); // NOI18N
        jLabelLucesMesa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabelLucesMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 220, 160, 312));

        jLabelLucesMueble01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/lucesMuebleA.png"))); // NOI18N
        add(jLabelLucesMueble01, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 160, 110, 70));

        jLabelLucesMueble02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/lucesMuebleB.png"))); // NOI18N
        add(jLabelLucesMueble02, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 159, -1, -1));

        jLabelLucesMueble03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/lucesMuebleC.png"))); // NOI18N
        add(jLabelLucesMueble03, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 159, 110, 80));

        jLabelLucesComedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/lucesComedor01.png"))); // NOI18N
        add(jLabelLucesComedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 130, 160));

        jLabelLucesComedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/lucesComedor02.png"))); // NOI18N
        jLabelLucesComedor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLucesComedor2MouseClicked(evt);
            }
        });
        add(jLabelLucesComedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 215, 140, 100));

        jLabelLucesSofa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLucesSofa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/lucesSofa.png"))); // NOI18N
        jLabelLucesSofa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabelLucesSofa, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 310, -1, -1));

        jLabelPersiana1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/persianas1.png"))); // NOI18N
        add(jLabelPersiana1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 145, -1, -1));

        jLabelPersiana2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/persianas2.png"))); // NOI18N
        add(jLabelPersiana2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 145, -1, -1));

        jLabelPersiana3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/persianas3.png"))); // NOI18N
        add(jLabelPersiana3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 145, -1, -1));

        jLabelPersiana4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPersiana4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/persianas4.png"))); // NOI18N
        add(jLabelPersiana4, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 145, -1, -1));

        jLabelAireAcondicionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/aireAcondicionado.png"))); // NOI18N
        jLabelAireAcondicionado.setToolTipText("");
        add(jLabelAireAcondicionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 76, 140, -1));

        jLabelRadiador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/radiadorPared.png"))); // NOI18N
        jLabelRadiador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabelRadiador, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 331, -1, 100));
        add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 254, 130, 110));

        jLabelTelevisor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/televisor1.png"))); // NOI18N
        add(jLabelTelevisor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 260, 120, 105));

        jLabelTiempoCM.setFont(getLedFont());
        jLabelTiempoCM.setForeground(new java.awt.Color(204, 0, 0));
        jLabelTiempoCM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTiempoCM.setAlignmentX(0.5F);
        jLabelTiempoCM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabelTiempoCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 70, 30));

        jLabelMiniCadena1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/miniCadena1.png"))); // NOI18N
        add(jLabelMiniCadena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 289, 70, 60));

        jLabelTiempoBR.setFont(getLedFont());
        jLabelTiempoBR.setForeground(new java.awt.Color(255, 255, 51));
        jLabelTiempoBR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTiempoBR.setAlignmentX(0.5F);
        jLabelTiempoBR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabelTiempoBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 312, 90, 30));

        jLabelBlueRay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/bluRay1.png"))); // NOI18N
        add(jLabelBlueRay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 311, 80, 50));

        jLabelFondoV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/SalonComedor.png"))); // NOI18N
        jLabelFondoV1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabelFondoV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelLucesComedor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLucesComedor2MouseClicked

    }//GEN-LAST:event_jLabelLucesComedor2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabeLuceslEntrada;
    private javax.swing.JLabel jLabelAireAcondicionado;
    private javax.swing.JLabel jLabelBlueRay1;
    private javax.swing.JLabel jLabelFondoV1;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelLucesComedor1;
    private javax.swing.JLabel jLabelLucesComedor2;
    private javax.swing.JLabel jLabelLucesMesa;
    private javax.swing.JLabel jLabelLucesMueble01;
    private javax.swing.JLabel jLabelLucesMueble02;
    private javax.swing.JLabel jLabelLucesMueble03;
    private javax.swing.JLabel jLabelLucesSofa;
    private javax.swing.JLabel jLabelMiniCadena1;
    private javax.swing.JLabel jLabelPersiana1;
    private javax.swing.JLabel jLabelPersiana2;
    private javax.swing.JLabel jLabelPersiana3;
    private javax.swing.JLabel jLabelPersiana4;
    private javax.swing.JLabel jLabelRadiador;
    private javax.swing.JLabel jLabelTelevisor1;
    private javax.swing.JLabel jLabelTiempoBR;
    private javax.swing.JLabel jLabelTiempoCM;
    // End of variables declaration//GEN-END:variables

}
