/*
 * VentanaPrincipal.java
 */
package net.ausiasmarch.habitacion.gui;

import javax.swing.UIManager;
import javax.swing.JFrame;
import javax.swing.UnsupportedLookAndFeelException;
import net.ausiasmarch.habitacion.modelo.*;

/**
 *
 * @author anon
 */
public class VentanaPrincipal extends JFrame implements ProbadorAparatos {

    private Controlador controlador;

    // Declaramos las variables para los aparatos
    private AireAcondicionado aireAcondicionado;
    private BluRay bluRay;
    private CadenaMusica cadenaMusica;
    private Lampara lamparaEntrada, lamparaMesa, lamparaMueble, lamparaMueble2,
            lamparaMueble3, lamparaTecho1, lamparaTecho2, lamparaSofa;
    private Persiana persiana;
    private Radiador radiador;
    private Televisor televisor;
    
    /**
     * Constructor
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public VentanaPrincipal() {
        initComponents();
        iniciar();
    }

    // Iniciamos los aparatos
    private void iniciar() {
        controlador = new Controlador(this);

        // Creamos los aparatos
        lamparaEntrada = new Lampara(0);
        lamparaMesa = new Lampara(1);
        lamparaMueble = new Lampara(2);
        lamparaMueble2 = new Lampara(3);
        lamparaMueble3 = new Lampara(4);
        lamparaTecho1 = new Lampara(5);
        lamparaTecho2 = new Lampara(6);
        lamparaSofa = new Lampara(7);
        persiana = new Persiana(8);
        aireAcondicionado = new AireAcondicionado(12);
        radiador = new Radiador(13);
        televisor = new Televisor(15);
        cadenaMusica = new CadenaMusica(17);
        bluRay = new BluRay(19);
        
        // Asignamos la habitacion a cada aparato
        lamparaEntrada.setHabitacion(habitacion);
        lamparaMesa.setHabitacion(habitacion);
        lamparaMueble.setHabitacion(habitacion);
        lamparaMueble2.setHabitacion(habitacion);
        lamparaMueble3.setHabitacion(habitacion);
        lamparaTecho1.setHabitacion(habitacion);
        lamparaTecho2.setHabitacion(habitacion);
        lamparaSofa.setHabitacion(habitacion);
        persiana.setHabitacion(habitacion);
        aireAcondicionado.setHabitacion(habitacion);
        radiador.setHabitacion(habitacion);
        televisor.setHabitacion(habitacion);
        cadenaMusica.setHabitacion(habitacion);
        bluRay.setHabitacion(habitacion);
        
        // Subimos la persiana
        persiana.subir();
        
        // Desactiva boton apagar 
        jButtonParar.setEnabled(false);

        setSize(900, 770);           // Tamaño de la ventana
        setVisible(true);            // Ventana visible
        setLocationRelativeTo(null); // Ventana centrada en pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneHabitacion = new javax.swing.JTabbedPane();
        jPanelVistaGeneral = new javax.swing.JPanel();
        jSliderRegulador = new javax.swing.JSlider();
        jButtonProbarAparatos = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonParar = new javax.swing.JButton();
        jLabelLamparaTecho2 = new javax.swing.JLabel();
        habitacion = new net.ausiasmarch.habitacion.modelo.Habitacion();
        jPanelControl = new javax.swing.JPanel();
        jToggelLucesMesa = new javax.swing.JToggleButton();
        jToggelLucesMueble = new javax.swing.JToggleButton();
        jToggelLucesComedor1 = new javax.swing.JToggleButton();
        jToggelLucesComedor2 = new javax.swing.JToggleButton();
        jToggelLucesSofa = new javax.swing.JToggleButton();
        jToggelLucesEntrada = new javax.swing.JToggleButton();
        jToggelRadiador = new javax.swing.JToggleButton();
        jToggelAireAcondicionado = new javax.swing.JToggleButton();
        jToggelMiniCadena = new javax.swing.JToggleButton();
        jToggelBluRay = new javax.swing.JToggleButton();
        jToggelTelevisor = new javax.swing.JToggleButton();
        jToggelPersianaSubir = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Habitación Inteligente");
        setMinimumSize(new java.awt.Dimension(1020, 668));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelVistaGeneral.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVistaGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSliderRegulador.setMajorTickSpacing(1);
        jSliderRegulador.setMaximum(3);
        jSliderRegulador.setPaintLabels(true);
        jSliderRegulador.setPaintTicks(true);
        jSliderRegulador.setValue(0);
        jSliderRegulador.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderReguladorStateChanged(evt);
            }
        });
        jPanelVistaGeneral.add(jSliderRegulador, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        jButtonProbarAparatos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonProbarAparatos.setText("Probar Aparatos");
        jButtonProbarAparatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProbarAparatosActionPerformed(evt);
            }
        });
        jPanelVistaGeneral.add(jButtonProbarAparatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 150, 30));

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelVistaGeneral.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 173, 150, 30));

        jButtonParar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonParar.setText("Parar prueba");
        jButtonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPararActionPerformed(evt);
            }
        });
        jPanelVistaGeneral.add(jButtonParar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 150, 30));
        jPanelVistaGeneral.add(jLabelLamparaTecho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 70, 90));

        habitacion.setBackground(new java.awt.Color(255, 255, 255));
        habitacion.setToolTipText("");
        jPanelVistaGeneral.add(habitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1010, 580));

        jPanelControl.setBackground(new java.awt.Color(51, 51, 51));
        jPanelControl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggelLucesMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_LamparaMesaOFF.png"))); // NOI18N
        jToggelLucesMesa.setToolTipText("Luces de la Mesa");
        jToggelLucesMesa.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToggelLucesMesa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggelLucesMesa.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggelLucesMesa.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggelLucesMesa.setPreferredSize(new java.awt.Dimension(50, 50));
        jToggelLucesMesa.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_LamparaMesaON.png"))); // NOI18N
        jToggelLucesMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggelLucesMesaActionPerformed(evt);
            }
        });
        jPanelControl.add(jToggelLucesMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jToggelLucesMueble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_LamparaMuebleOFF.png"))); // NOI18N
        jToggelLucesMueble.setToolTipText("Luces del Mueble");
        jToggelLucesMueble.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToggelLucesMueble.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggelLucesMueble.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggelLucesMueble.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggelLucesMueble.setPreferredSize(new java.awt.Dimension(50, 50));
        jToggelLucesMueble.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_LamparaMuebleON.png"))); // NOI18N
        jToggelLucesMueble.setVerifyInputWhenFocusTarget(false);
        jToggelLucesMueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggelLucesMuebleActionPerformed(evt);
            }
        });
        jPanelControl.add(jToggelLucesMueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 5, -1, 50));

        jToggelLucesComedor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggelLucesComedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_LamparaAVOFF.png"))); // NOI18N
        jToggelLucesComedor1.setText("1");
        jToggelLucesComedor1.setToolTipText("Luces Comedor 1");
        jToggelLucesComedor1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToggelLucesComedor1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggelLucesComedor1.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggelLucesComedor1.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggelLucesComedor1.setPreferredSize(new java.awt.Dimension(50, 50));
        jToggelLucesComedor1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_LamparaAVON.png"))); // NOI18N
        jToggelLucesComedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggelLucesComedor1ActionPerformed(evt);
            }
        });
        jPanelControl.add(jToggelLucesComedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 5, -1, 50));

        jToggelLucesComedor2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggelLucesComedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_LamparaAVOFF.png"))); // NOI18N
        jToggelLucesComedor2.setText("2");
        jToggelLucesComedor2.setToolTipText("Luces Comedor 2");
        jToggelLucesComedor2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToggelLucesComedor2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggelLucesComedor2.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggelLucesComedor2.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggelLucesComedor2.setPreferredSize(new java.awt.Dimension(50, 50));
        jToggelLucesComedor2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_LamparaAVON.png"))); // NOI18N
        jToggelLucesComedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggelLucesComedor2ActionPerformed(evt);
            }
        });
        jPanelControl.add(jToggelLucesComedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 5, -1, 50));

        jToggelLucesSofa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_LamparaSofaOFF.png"))); // NOI18N
        jToggelLucesSofa.setToolTipText("Luces Sofa");
        jToggelLucesSofa.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToggelLucesSofa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggelLucesSofa.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggelLucesSofa.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggelLucesSofa.setPreferredSize(new java.awt.Dimension(50, 50));
        jToggelLucesSofa.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_LamparaSofaON.png"))); // NOI18N
        jToggelLucesSofa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggelLucesSofaActionPerformed(evt);
            }
        });
        jPanelControl.add(jToggelLucesSofa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 5, -1, 50));

        jToggelLucesEntrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggelLucesEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_LamparaAVOFF.png"))); // NOI18N
        jToggelLucesEntrada.setText("E");
        jToggelLucesEntrada.setToolTipText("Luces Entrada");
        jToggelLucesEntrada.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToggelLucesEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggelLucesEntrada.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggelLucesEntrada.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggelLucesEntrada.setPreferredSize(new java.awt.Dimension(50, 50));
        jToggelLucesEntrada.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_LamparaAVON.png"))); // NOI18N
        jToggelLucesEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggelLucesEntradaActionPerformed(evt);
            }
        });
        jPanelControl.add(jToggelLucesEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 5, -1, 50));

        jToggelRadiador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggelRadiador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_RadiadorOFF.png"))); // NOI18N
        jToggelRadiador.setToolTipText("Radiador");
        jToggelRadiador.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToggelRadiador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggelRadiador.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggelRadiador.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggelRadiador.setPreferredSize(new java.awt.Dimension(50, 50));
        jToggelRadiador.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_RadiadorON.png"))); // NOI18N
        jToggelRadiador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggelRadiadorActionPerformed(evt);
            }
        });
        jPanelControl.add(jToggelRadiador, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 5, -1, 50));

        jToggelAireAcondicionado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggelAireAcondicionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_AireAcondicionadoOFF.png"))); // NOI18N
        jToggelAireAcondicionado.setToolTipText("Airea Acondicionado");
        jToggelAireAcondicionado.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToggelAireAcondicionado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggelAireAcondicionado.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggelAireAcondicionado.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggelAireAcondicionado.setPreferredSize(new java.awt.Dimension(50, 50));
        jToggelAireAcondicionado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_AireAcondicionadoON.png"))); // NOI18N
        jToggelAireAcondicionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggelAireAcondicionadoActionPerformed(evt);
            }
        });
        jPanelControl.add(jToggelAireAcondicionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 5, -1, 50));

        jToggelMiniCadena.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggelMiniCadena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_MCadenaOFF.png"))); // NOI18N
        jToggelMiniCadena.setToolTipText("MiniCadena de Música");
        jToggelMiniCadena.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToggelMiniCadena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggelMiniCadena.setIconTextGap(5);
        jToggelMiniCadena.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggelMiniCadena.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggelMiniCadena.setPreferredSize(new java.awt.Dimension(50, 50));
        jToggelMiniCadena.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_MCadenaON.png"))); // NOI18N
        jToggelMiniCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggelMiniCadenaActionPerformed(evt);
            }
        });
        jPanelControl.add(jToggelMiniCadena, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 5, -1, 50));

        jToggelBluRay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggelBluRay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_BluRayOFF.png"))); // NOI18N
        jToggelBluRay.setToolTipText("BluRay Vídeo");
        jToggelBluRay.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToggelBluRay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggelBluRay.setIconTextGap(5);
        jToggelBluRay.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggelBluRay.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggelBluRay.setPreferredSize(new java.awt.Dimension(50, 50));
        jToggelBluRay.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_BluRayON.png"))); // NOI18N
        jToggelBluRay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggelBluRayActionPerformed(evt);
            }
        });
        jPanelControl.add(jToggelBluRay, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 5, -1, 50));

        jToggelTelevisor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggelTelevisor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_TVOFF.png"))); // NOI18N
        jToggelTelevisor.setToolTipText("Televisor");
        jToggelTelevisor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToggelTelevisor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggelTelevisor.setIconTextGap(5);
        jToggelTelevisor.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggelTelevisor.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggelTelevisor.setPreferredSize(new java.awt.Dimension(50, 50));
        jToggelTelevisor.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_TVON.png"))); // NOI18N
        jToggelTelevisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggelTelevisorActionPerformed(evt);
            }
        });
        jPanelControl.add(jToggelTelevisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 5, -1, 50));

        jToggelPersianaSubir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggelPersianaSubir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_PersianaOFF.png"))); // NOI18N
        jToggelPersianaSubir.setToolTipText("Subir Persiana");
        jToggelPersianaSubir.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToggelPersianaSubir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggelPersianaSubir.setMaximumSize(new java.awt.Dimension(50, 50));
        jToggelPersianaSubir.setMinimumSize(new java.awt.Dimension(50, 50));
        jToggelPersianaSubir.setPreferredSize(new java.awt.Dimension(50, 50));
        jToggelPersianaSubir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/net/ausiasmarch/habitacion/recursos/btn_PersianaON.png"))); // NOI18N
        jToggelPersianaSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggelPersianaSubirActionPerformed(evt);
            }
        });
        jPanelControl.add(jToggelPersianaSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 5, -1, 50));

        jPanelVistaGeneral.add(jPanelControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 970, 60));

        jTabbedPaneHabitacion.addTab("Vista general Salón Comedor", jPanelVistaGeneral);

        getContentPane().add(jTabbedPaneHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 740));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton Probar los aparatos
     *
     * @param evt
     */
    private void jButtonProbarAparatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProbarAparatosActionPerformed
        controlador.iniciar();
        jButtonProbarAparatos.setEnabled(false);
        jButtonParar.setEnabled(true);
    }//GEN-LAST:event_jButtonProbarAparatosActionPerformed

    /**
     * Boton Salir de la aplicacion
     *
     * @param evt
     */
    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        salir();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * Cerrar la ventana
     *
     * @param evt
     */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        salir();
    }//GEN-LAST:event_formWindowClosed

    /**
     * Boton parar prueba
     *
     * @param evt
     */
    private void jButtonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPararActionPerformed
        botonesOnOff(true);
        detenerAparatos();
        controlador.parar();
        jButtonProbarAparatos.setEnabled(true);
        jButtonParar.setEnabled(false);
    }//GEN-LAST:event_jButtonPararActionPerformed

    /**
     * Boton Persiana
     *
     * @param evt
     */
    private void jToggelPersianaSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggelPersianaSubirActionPerformed
        if (persiana.isSubida()) {
           persiana.bajar();
       } else {
           persiana.subir();
       }
    }//GEN-LAST:event_jToggelPersianaSubirActionPerformed

    /**
     * Boton Televisor
     *
     * @param evt
     */
    private void jToggelTelevisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggelTelevisorActionPerformed
        if (televisor.isEncendido()) {
           televisor.apagar();
       } else {
           televisor.encender();
       }
    }//GEN-LAST:event_jToggelTelevisorActionPerformed

    /**
     * Boton BluRay
     *
     * @param evt
     */
    private void jToggelBluRayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggelBluRayActionPerformed
        if (bluRay.isPlay()) {
           bluRay.stop();
       } else {
           bluRay.play("My heart will go on.mp3", "Titanic.png", televisor);
       }
    }//GEN-LAST:event_jToggelBluRayActionPerformed

    /**
     * Boton Cadena de musica
     *
     * @param evt
     */
    private void jToggelMiniCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggelMiniCadenaActionPerformed
        if (cadenaMusica.isPlay()) {
           cadenaMusica.stop();
       } else {
           cadenaMusica.play("Imagine.mp3");
       }
    }//GEN-LAST:event_jToggelMiniCadenaActionPerformed

    /**
     * Boton Aire acondicionado
     *
     * @param evt
     */
    private void jToggelAireAcondicionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggelAireAcondicionadoActionPerformed
        if (aireAcondicionado.isEncendido()) {
           aireAcondicionado.apagar();
       } else {
           aireAcondicionado.enfriar();
       }
    }//GEN-LAST:event_jToggelAireAcondicionadoActionPerformed

    /**
     * Boton Radiador
     */
    private void jToggelRadiadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggelRadiadorActionPerformed
        if (radiador.isEncendido()) {
           radiador.apagar();
       } else {
           radiador.calentar();
       }
    }//GEN-LAST:event_jToggelRadiadorActionPerformed

    /**
     * Boton Lampara entrada
     *
     * @param evt
     */
    private void jToggelLucesEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggelLucesEntradaActionPerformed
       if (lamparaEntrada.isEncendida()) {
           lamparaEntrada.apagar();
       } else {
           lamparaEntrada.encender();
       }
    }//GEN-LAST:event_jToggelLucesEntradaActionPerformed

    /**
     * Boton lampara sofa
     *
     * @param evt
     */
    private void jToggelLucesSofaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggelLucesSofaActionPerformed
        if (lamparaSofa.isEncendida()) {
           lamparaSofa.apagar();
       } else {
           lamparaSofa.encender();
       }
    }//GEN-LAST:event_jToggelLucesSofaActionPerformed

    /**
     * Boton Lampara techo 2
     *
     * @param evt
     */
    private void jToggelLucesComedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggelLucesComedor2ActionPerformed
        if (lamparaTecho2.isEncendida()) {
           lamparaTecho2.apagar();
       } else {
           lamparaTecho2.encender();
       }
    }//GEN-LAST:event_jToggelLucesComedor2ActionPerformed

    /**
     * Boton lampara techo 1
     *
     * @param evt
     */
    private void jToggelLucesComedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggelLucesComedor1ActionPerformed
       if (lamparaTecho1.isEncendida()) {
           lamparaTecho1.apagar();
       } else {
           lamparaTecho1.encender();
       }
    }//GEN-LAST:event_jToggelLucesComedor1ActionPerformed

    /**
     * Boton Lampara mueble
     *
     * @param evt
     */
    private void jToggelLucesMuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggelLucesMuebleActionPerformed
       if (lamparaMueble.isEncendida()) {
           lamparaMueble.apagar();
       } else {
           lamparaMueble.encender();
       }
    }//GEN-LAST:event_jToggelLucesMuebleActionPerformed

    private void jToggelLucesMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggelLucesMesaActionPerformed
       if (lamparaMesa.isEncendida()) {
           lamparaMesa.apagar();
       } else {
           lamparaMesa.encender();
       }
    }//GEN-LAST:event_jToggelLucesMesaActionPerformed

    /* Añadido un jSlider para mostrar las tres intensidades de la lampara
    *  del mueble.
    *  Valores del jSlider cambiados de 0 a 3. */
    private void jSliderReguladorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderReguladorStateChanged
        int intensidad = jSliderRegulador.getValue();
        switch (intensidad) {
            case 0:
                lamparaMueble.apagar();
                lamparaMueble2.apagar();
                lamparaMueble3.apagar();
                break;
            case 1:
                lamparaMueble.encender();
                break;
            case 2:
                lamparaMueble.apagar();
                lamparaMueble2.encender();
                break;
            case 3:
                lamparaMueble2.apagar();
                lamparaMueble3.encender();
                break;
        }
    }//GEN-LAST:event_jSliderReguladorStateChanged

    /**
     * Detener los aparatos
     */
    private void detenerAparatos() {
        apagarAudioVideo();
        lamparaEntrada.apagar();
        lamparaMesa.apagar();
        lamparaMueble.apagar();
        lamparaTecho1.apagar();
        lamparaTecho2.apagar();
        lamparaSofa.apagar();
        persiana.subir();
        aireAcondicionado.apagar();
        radiador.apagar();
        televisor.apagar();
    }

    /**
     * Apagar audio y video
     */
    private void apagarAudioVideo() {
        if (cadenaMusica.isPlay()) {
            cadenaMusica.stop();
        }
        
        if (bluRay.isPlay()) {
            bluRay.stop();
        }
    }

    /**
     * Salir de la aplicacion
     */
    private void salir() {
       System.exit(0);
    }

    /**
     * Parar
     */
    private void parar() {
        botonesOnOff(true);
        detenerAparatos();

        jButtonProbarAparatos.setEnabled(true);
        jButtonParar.setEnabled(false);
    }

    // Prueba los aparatos 
    @Override
    public void pruebaAparatos() {
        Lampara lampara;
        botonesOnOff(false);
        apagarAudioVideo();
        
        for (int i = 0; i <= 7; i++) {
            if (controlador.getProbar() == false) {
                return;
            }
            lampara = new Lampara(i);
            lampara.setHabitacion(habitacion);
            lampara.encender();
            pausa(2000);
        }
        
        pausa(10000);
        
        for (int j = 7; j >= 0; j--) {
            if (controlador.getProbar() == false) {
                return;
            }
            lampara = new Lampara(j);
            lampara.setHabitacion(habitacion);
            lampara.apagar();
            pausa(2000);
        }
        
        pausa(10000);
        
        for (int k = 0; k <= 7; k++) {
            if (controlador.getProbar() == false) {
                return;
            }
            
            lampara = new Lampara(k);
            lampara.setHabitacion(habitacion);
            lampara.encender();
            
            // Añadidas las intensidades al bucle "probarAparatos"
            switch (k) {
                case 2:
                    lampara.apagar();
                    pausa(1000);
                    lampara.encender();
                        if (lampara.isEncendida()) {
                            lamparaMueble.encender();
                            pausa(2000);
                            lamparaMueble.apagar();
                            lamparaMueble2.encender();
                            pausa(2000);
                            lamparaMueble2.apagar();
                            lamparaMueble3.encender();
                            pausa(2000);
                            lamparaMueble3.apagar();
                        }
                    persiana.bajar();
                    pausa(2000);
                    radiador.calentar();
                    pausa(2000);
                    cadenaMusica.play("Imagine.mp3");
                    pausa(20000);
                    cadenaMusica.stop();
                    break;
                case 7:
                    bluRay.play("My heart will go on.mp3", "Titanic.png", 
                            televisor);
                    pausa(15000);
                    bluRay.stop();
                    radiador.apagar();
                    break;
            }
            
            lampara.apagar();
            pausa(1000);
        }
        
        botonesOnOff(true);
    }

    /**
     * Activa y desactiva los botones
     *
     * @param sn
     *
     * Añadido el activador/desactivador del jSlider **/
    private void botonesOnOff(boolean sn) {
        jToggelLucesEntrada.setEnabled(sn);
        jToggelLucesMesa.setEnabled(sn);
        jToggelLucesMueble.setEnabled(sn);
        jToggelLucesComedor1.setEnabled(sn);
        jToggelLucesComedor2.setEnabled(sn);
        jToggelLucesSofa.setEnabled(sn);
        jToggelMiniCadena.setEnabled(sn);
        jToggelBluRay.setEnabled(sn);
        jSliderRegulador.setEnabled(sn);
        jToggelPersianaSubir.setEnabled(sn);
        jToggelTelevisor.setEnabled(sn);
        jToggelRadiador.setEnabled(sn);
        jToggelAireAcondicionado.setEnabled(sn);
    }

    /**
     * Hace una pausa en milisegundos
     *
     * @param sleep
     */
    private void pausa(int sleep) {
        try {
            Thread.sleep(sleep);
        } catch (InterruptedException ex) {
            throw new RuntimeException(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException |
                IllegalAccessException | UnsupportedLookAndFeelException e) {
            //No hacemos nada, que se quede como está
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            @SuppressWarnings("ResultOfObjectAllocationIgnored")
            public void run() {
                new VentanaPrincipal();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.ausiasmarch.habitacion.modelo.Habitacion habitacion;
    private javax.swing.JButton jButtonParar;
    private javax.swing.JButton jButtonProbarAparatos;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelLamparaTecho2;
    private javax.swing.JPanel jPanelControl;
    private javax.swing.JPanel jPanelVistaGeneral;
    private javax.swing.JSlider jSliderRegulador;
    private javax.swing.JTabbedPane jTabbedPaneHabitacion;
    private javax.swing.JToggleButton jToggelAireAcondicionado;
    private javax.swing.JToggleButton jToggelBluRay;
    private javax.swing.JToggleButton jToggelLucesComedor1;
    private javax.swing.JToggleButton jToggelLucesComedor2;
    private javax.swing.JToggleButton jToggelLucesEntrada;
    private javax.swing.JToggleButton jToggelLucesMesa;
    private javax.swing.JToggleButton jToggelLucesMueble;
    private javax.swing.JToggleButton jToggelLucesSofa;
    private javax.swing.JToggleButton jToggelMiniCadena;
    private javax.swing.JToggleButton jToggelPersianaSubir;
    private javax.swing.JToggleButton jToggelRadiador;
    private javax.swing.JToggleButton jToggelTelevisor;
    // End of variables declaration//GEN-END:variables
}