package net.ausiasmarch.validaciones.gui;

import java.awt.Color;
import javax.swing.JOptionPane;
import net.ausiasmarch.validaciones.modelo.*;

/**
 * Main.java
 *
 * @author Luis
 */
public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
        inicio();
    }

    private void inicio() {       
        pack();
        setLocationRelativeTo(null);
        jTextFieldEMail.requestFocus();
        jTextFieldNifNie.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelValidator = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelNumeros = new javax.swing.JPanel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButtonValidarNumero = new javax.swing.JButton();
        jTextFieldValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanelEMail = new javax.swing.JPanel();
        jTextFieldEMail = new javax.swing.JTextField();
        jButtonValidaEMail = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanelNifNie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNifNie = new javax.swing.JTextField();
        jButtonValidaNifNie = new javax.swing.JButton();
        jPanelIBAN = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCCC = new javax.swing.JTextField();
        jButtonValidaCCC = new javax.swing.JButton();
        jTextFieldIBAN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Validaciones");
        setResizable(false);

        jPanelValidator.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelNumeros.setBackground(new java.awt.Color(255, 255, 255));

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Integer", "Double" }));

        jLabel5.setText("Tipo");

        jButtonValidarNumero.setText("Validar");
        jButtonValidarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarNumeroActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor");

        javax.swing.GroupLayout jPanelNumerosLayout = new javax.swing.GroupLayout(jPanelNumeros);
        jPanelNumeros.setLayout(jPanelNumerosLayout);
        jPanelNumerosLayout.setHorizontalGroup(
            jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumerosLayout.createSequentialGroup()
                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNumerosLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldValor)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelNumerosLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jButtonValidarNumero)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanelNumerosLayout.setVerticalGroup(
            jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNumerosLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addComponent(jButtonValidarNumero)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Validar Números", jPanelNumeros);

        jPanelEMail.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldEMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEMailFocusGained(evt);
            }
        });

        jButtonValidaEMail.setText("Validar");
        jButtonValidaEMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidaEMailActionPerformed(evt);
            }
        });

        jLabel3.setText("E-Mail");

        javax.swing.GroupLayout jPanelEMailLayout = new javax.swing.GroupLayout(jPanelEMail);
        jPanelEMail.setLayout(jPanelEMailLayout);
        jPanelEMailLayout.setHorizontalGroup(
            jPanelEMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEMailLayout.createSequentialGroup()
                .addGroup(jPanelEMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEMailLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanelEMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldEMail, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelEMailLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jButtonValidaEMail)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanelEMailLayout.setVerticalGroup(
            jPanelEMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEMailLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButtonValidaEMail)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Validar EMail", jPanelEMail);

        jPanelNifNie.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("NIF/NIE:");

        jTextFieldNifNie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNifNieFocusGained(evt);
            }
        });

        jButtonValidaNifNie.setText("Validar");
        jButtonValidaNifNie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidaNifNieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNifNieLayout = new javax.swing.GroupLayout(jPanelNifNie);
        jPanelNifNie.setLayout(jPanelNifNieLayout);
        jPanelNifNieLayout.setHorizontalGroup(
            jPanelNifNieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNifNieLayout.createSequentialGroup()
                .addGroup(jPanelNifNieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNifNieLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNifNie, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelNifNieLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jButtonValidaNifNie)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanelNifNieLayout.setVerticalGroup(
            jPanelNifNieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNifNieLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanelNifNieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNifNie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButtonValidaNifNie)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Validar NIF o NIE", jPanelNifNie);

        jPanelIBAN.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Codigo Cuenta Cliente");

        jButtonValidaCCC.setText("Validar");
        jButtonValidaCCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidaCCCActionPerformed(evt);
            }
        });

        jTextFieldIBAN.setEditable(false);
        jTextFieldIBAN.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setText("IBAN");

        javax.swing.GroupLayout jPanelIBANLayout = new javax.swing.GroupLayout(jPanelIBAN);
        jPanelIBAN.setLayout(jPanelIBANLayout);
        jPanelIBANLayout.setHorizontalGroup(
            jPanelIBANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIBANLayout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(jButtonValidaCCC)
                .addGap(249, 249, 249))
            .addGroup(jPanelIBANLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanelIBANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanelIBANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldCCC)
                        .addComponent(jTextFieldIBAN, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelIBANLayout.setVerticalGroup(
            jPanelIBANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIBANLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButtonValidaCCC)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Validar IBAN", jPanelIBAN);

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelValidatorLayout = new javax.swing.GroupLayout(jPanelValidator);
        jPanelValidator.setLayout(jPanelValidatorLayout);
        jPanelValidatorLayout.setHorizontalGroup(
            jPanelValidatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelValidatorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLimpiar)
                .addGap(50, 50, 50)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanelValidatorLayout.setVerticalGroup(
            jPanelValidatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelValidatorLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanelValidatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonLimpiar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelValidator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelValidator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonValidaNifNieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidaNifNieActionPerformed
        String nifNie = jTextFieldNifNie.getText();
        try {
            Nif.valida(nifNie);
            jTextFieldNifNie.setForeground(Color.BLUE);
            jTextFieldNifNie.setText(nifNie.toUpperCase());
        } catch (Exception ex) {
            jTextFieldNifNie.setForeground(Color.RED);
            mensaje(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonValidaNifNieActionPerformed

    private void jTextFieldNifNieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNifNieFocusGained
        jTextFieldNifNie.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTextFieldNifNieFocusGained

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextFieldNifNie.setText("");
        jTextFieldEMail.setText("");
        jTextFieldCCC.setText("");
        jTextFieldIBAN.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonValidaEMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidaEMailActionPerformed
        String EMail = jTextFieldEMail.getText();
        try {
            Email.valida(EMail);
            jTextFieldEMail.setForeground(Color.BLUE);
        } catch (Exception ex) {
            jTextFieldEMail.setForeground(Color.RED);
            mensaje(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonValidaEMailActionPerformed

    private void jButtonValidaCCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidaCCCActionPerformed

        
        
        
    }//GEN-LAST:event_jButtonValidaCCCActionPerformed

    private void jTextFieldEMailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEMailFocusGained
        jTextFieldEMail.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTextFieldEMailFocusGained

    private void jButtonValidarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarNumeroActionPerformed
        String Numero = jTextFieldValor.getText();
        try {
            if (!Convert.isValidInt(Numero)) {
                mensaje(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonValidarNumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void mensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonValidaCCC;
    private javax.swing.JButton jButtonValidaEMail;
    private javax.swing.JButton jButtonValidaNifNie;
    private javax.swing.JButton jButtonValidarNumero;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelEMail;
    private javax.swing.JPanel jPanelIBAN;
    private javax.swing.JPanel jPanelNifNie;
    private javax.swing.JPanel jPanelNumeros;
    private javax.swing.JPanel jPanelValidator;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldCCC;
    private javax.swing.JTextField jTextFieldEMail;
    private javax.swing.JTextField jTextFieldIBAN;
    private javax.swing.JTextField jTextFieldNifNie;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}